var num1 = 200;
var namestr = "test";
var tbool = true;
var anytype = "test";
console.log("number :", num1);
console.log("name string : ", namestr);
console.log("tbl: ", tbool);
console.log("anytype:", anytype);
anytype = true;
console.log("changed data", anytype);
anytype = 500;
console.log("changed data", anytype);
